/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Owner;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import app.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author asus
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    String produkTerlaris;
    int jumlahTerjual;
    double totalPenjualan;
    public Product() {
        initComponents();
        loadProdukTerlarisBulanIni();
        loadProdukTerjualBulanIni();
        loadPendapatanBulanIni();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProdukTerlaris = new javax.swing.JLabel();
        lblTotalTerjual = new javax.swing.JLabel();
        lblTotalPendapatan = new javax.swing.JLabel();
        tglDari = new com.toedter.calendar.JDateChooser();
        tglSampai = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdukTerjual = new javax.swing.JTable();
        tglSampai2 = new com.toedter.calendar.JDateChooser();
        tglDari2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalPendapatan2 = new javax.swing.JLabel();
        tglDariPendapatan = new com.toedter.calendar.JDateChooser();
        tglSampaiPendapatan = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produk terlaris");

        lblProdukTerlaris.setText("jLabel2");

        lblTotalTerjual.setText("jLabel2");

        lblTotalPendapatan.setText("jLabel2");

        jLabel2.setText("dari");

        jLabel3.setText("sampai");

        jButton1.setText("view");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblProdukTerlaris))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTotalTerjual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(tglDari, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)
                                .addComponent(jButton1)))))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblTotalPendapatan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblProdukTerlaris)
                        .addGap(20, 20, 20)
                        .addComponent(lblTotalTerjual)
                        .addGap(30, 30, 30)
                        .addComponent(lblTotalPendapatan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        jTableProdukTerjual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Produk", "Jumlah Terjual", "Total Pendapatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProdukTerjual);

        jButton3.setText("view");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("refreh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("dari");

        jLabel5.setText("sampai");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        lblTotalPendapatan2.setText("jLabel6");

        jLabel7.setText("Sampai");

        jLabel8.setText("Dari");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Pnedapatn");

        jButton5.setText("view");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglDariPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglSampaiPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTotalPendapatan2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton5)
                        .addGap(35, 35, 35)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(lblTotalPendapatan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglSampaiPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglDariPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tglDari2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(tglSampai2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel5))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglDari2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglSampai2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadProdukTerlarisCustomPeriode();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadProdukTerlarisBulanIni();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadProdukTerjualCustomPeriode();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadProdukTerjualBulanIni();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loadPendapatanCustomPeriode();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        loadPendapatanBulanIni();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdukTerjual;
    private javax.swing.JLabel lblProdukTerlaris;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JLabel lblTotalPendapatan2;
    private javax.swing.JLabel lblTotalTerjual;
    private com.toedter.calendar.JDateChooser tglDari;
    private com.toedter.calendar.JDateChooser tglDari2;
    private com.toedter.calendar.JDateChooser tglDariPendapatan;
    private com.toedter.calendar.JDateChooser tglSampai;
    private com.toedter.calendar.JDateChooser tglSampai2;
    private com.toedter.calendar.JDateChooser tglSampaiPendapatan;
    // End of variables declaration//GEN-END:variables
    private void loadProdukTerlarisBulanIni() {
    try {
        Connection conn = Koneksi.Go();

        // Ambil tanggal awal dan akhir bulan ini
        LocalDate now = LocalDate.now();
        String tanggalAwal = now.withDayOfMonth(1).toString(); // Tanggal 1 bulan ini
        String tanggalAkhir = now.withDayOfMonth(now.lengthOfMonth()).toString(); // Tanggal terakhir bulan ini

        String sql = "SELECT " +
                     "p.nama_produk AS produk_terlaris, " +
                     "SUM(d.jumlah_produk) AS jumlah_terjual, " +
                     "SUM(d.jumlah_produk * p.harga_jual) AS total_penjualan " +
                     "FROM transaksi_detail d " +
                     "JOIN produk p ON d.id_produk = p.id_produk " +
                     "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                     "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ? " +
                     "GROUP BY p.nama_produk " +
                     "ORDER BY jumlah_terjual DESC " +
                     "LIMIT 1";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, tanggalAwal);
        stmt.setString(2, tanggalAkhir);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            produkTerlaris = rs.getString("produk_terlaris");
            jumlahTerjual = rs.getInt("jumlah_terjual");
            totalPenjualan = rs.getDouble("total_penjualan");
            
            loadData();

        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada data produk terlaris untuk bulan ini.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

        rs.close();
        stmt.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data produk terlaris bulan ini!", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
    private void loadProdukTerlarisCustomPeriode() {
        java.util.Date dateFrom = tglDari.getDate();
        java.util.Date dateTo = tglSampai.getDate();

        if (dateFrom == null || dateTo == null) {
            JOptionPane.showMessageDialog(this, "Harap pilih tanggal awal dan tanggal akhir!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Format tanggal ke bentuk SQL (yyyy-MM-dd)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariTanggal = sdf.format(dateFrom);
        String sampaiTanggal = sdf.format(dateTo);


        try {
            Connection conn = Koneksi.Go();

            String sql = "SELECT " +
                         "p.nama_produk AS produk_terlaris, " +
                         "SUM(d.jumlah_produk) AS jumlah_terjual, " +
                         "SUM(d.jumlah_produk * p.harga_jual) AS total_penjualan " +
                         "FROM transaksi_detail d " +
                         "JOIN produk p ON d.id_produk = p.id_produk " +
                         "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                         "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ? " +
                         "GROUP BY p.nama_produk " +
                         "ORDER BY jumlah_terjual DESC " +
                         "LIMIT 1";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, dariTanggal);
            stmt.setString(2, sampaiTanggal);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                produkTerlaris = rs.getString("produk_terlaris");
                jumlahTerjual = rs.getInt("jumlah_terjual");
                totalPenjualan = rs.getDouble("total_penjualan");
                
                loadData();

            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data produk terlaris untuk periode ini.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data produk terlaris!", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void loadData() {
            lblProdukTerlaris.setText(produkTerlaris);
            lblTotalTerjual.setText(jumlahTerjual+" terjual");
            lblTotalPendapatan.setText(String.format("Rp %, .2f", totalPenjualan));    
    }

    private void loadProdukTerjualCustomPeriode() {
        
        java.util.Date dateFrom = tglDari2.getDate();
        java.util.Date dateTo = tglSampai2.getDate();

        if (dateFrom == null || dateTo == null) {
            JOptionPane.showMessageDialog(this, "Harap pilih tanggal awal dan tanggal akhir!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Format tanggal ke bentuk SQL (yyyy-MM-dd)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariTanggal = sdf.format(dateFrom);
        String sampaiTanggal = sdf.format(dateTo);

        try {
            Connection conn = Koneksi.Go();

            String sql = "SELECT " +
                         "p.nama_produk AS nama_produk, " +
                         "SUM(d.jumlah_produk) AS jumlah_terjual, " +
                         "SUM(d.jumlah_produk * p.harga_jual) AS total_pendapatan " +
                         "FROM transaksi_detail d " +
                         "JOIN produk p ON d.id_produk = p.id_produk " +
                         "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                         "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ? " +
                         "GROUP BY p.nama_produk " +
                         "ORDER BY jumlah_terjual DESC";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, dariTanggal);
            stmt.setString(2, sampaiTanggal);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTableProdukTerjual.getModel();
            model.setRowCount(0); // Kosongkan tabel sebelum memuat data baru

            while (rs.next()) {

                String namaProduk = rs.getString("nama_produk");
                int jumlahTerjual = rs.getInt("jumlah_terjual");
                double totalPendapatan = rs.getDouble("total_pendapatan");
           
                

                model.addRow(new Object[]{namaProduk, jumlahTerjual, String.format("Rp %, .2f", totalPendapatan)});
            }
            System.out.println(dariTanggal);
            System.out.println(sampaiTanggal);
            System.out.println(sampaiTanggal);

            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data produk terjual!", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
}

    private void loadProdukTerjualBulanIni() {
   // Mengambil tanggal 1 bulan ini
    LocalDate now = LocalDate.now();
    LocalDate startOfMonth = now.withDayOfMonth(1); // Tanggal 1 bulan ini
    LocalDate today = now; // Hari ini

    // Format ke bentuk SQL (yyyy-MM-dd)
    String dariTanggal = startOfMonth.toString();
    String sampaiTanggal = today.toString();

    try {
        Connection conn = Koneksi.Go();

        String sql = "SELECT " +
                     "p.nama_produk AS nama_produk, " +
                     "SUM(d.jumlah_produk) AS jumlah_terjual, " +
                     "SUM(d.jumlah_produk * p.harga_jual) AS total_pendapatan " +
                     "FROM transaksi_detail d " +
                     "JOIN produk p ON d.id_produk = p.id_produk " +
                     "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                     "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ? " +
                     "GROUP BY p.nama_produk " +
                     "ORDER BY jumlah_terjual DESC";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, dariTanggal);
        stmt.setString(2, sampaiTanggal);

        ResultSet rs = stmt.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTableProdukTerjual.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum memuat data baru

        while (rs.next()) {
            String namaProduk = rs.getString("nama_produk");
            int jumlahTerjual = rs.getInt("jumlah_terjual");
            double totalPendapatan = rs.getDouble("total_pendapatan");

            model.addRow(new Object[]{namaProduk, jumlahTerjual,  String.format("Rp %, .2f", totalPendapatan)});
        }

        rs.close();
        stmt.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data produk terjual (default)!", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }    }

    private void loadPendapatanCustomPeriode() {
    java.util.Date dateFrom = tglDariPendapatan.getDate();
    java.util.Date dateTo = tglSampaiPendapatan.getDate();

    if (dateFrom == null || dateTo == null) {
        JOptionPane.showMessageDialog(this, "Harap pilih tanggal awal dan tanggal akhir!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Format tanggal ke bentuk SQL (yyyy-MM-dd)
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String dariTanggal = sdf.format(dateFrom);
    String sampaiTanggal = sdf.format(dateTo);

    try {
        Connection conn = Koneksi.Go();

        String sql = "SELECT SUM(d.jumlah_produk * p.harga_jual) AS total_pendapatan " +
                     "FROM transaksi_detail d " +
                     "JOIN produk p ON d.id_produk = p.id_produk " +
                     "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                     "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ?";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, dariTanggal);
        stmt.setString(2, sampaiTanggal);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            double totalPendapatan = rs.getDouble("total_pendapatan");
            lblTotalPendapatan2.setText(String.format("Rp %, .2f", totalPendapatan)); // Format untuk ditampilkan
        } else {
            lblTotalPendapatan2.setText("Rp 0");
        }

        rs.close();
        stmt.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data pendapatan!", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }}

    private void loadPendapatanBulanIni() {
    LocalDate now = LocalDate.now();
    LocalDate startOfMonth = now.withDayOfMonth(1); // Tanggal 1 bulan ini
    LocalDate today = now; // Hari ini

    // Format ke bentuk SQL (yyyy-MM-dd)
    String dariTanggal = startOfMonth.toString();
    String sampaiTanggal = today.toString();
    try {
        Connection conn = Koneksi.Go();

        String sql = "SELECT SUM(d.jumlah_produk * p.harga_jual) AS total_pendapatan " +
                     "FROM transaksi_detail d " +
                     "JOIN produk p ON d.id_produk = p.id_produk " +
                     "JOIN transaksi t ON d.id_transaksi = t.id_transaksi " +
                     "WHERE t.tanggal_transaksi >= ? AND t.tanggal_transaksi <= ?";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, dariTanggal);
        stmt.setString(2, sampaiTanggal);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            double totalPendapatan = rs.getDouble("total_pendapatan");
            lblTotalPendapatan2.setText(String.format("Rp %, .2f", totalPendapatan)); // Format untuk ditampilkan
        } else {
            lblTotalPendapatan2.setText("Rp 0");
        }

        rs.close();
        stmt.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data pendapatan!", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }    }


}
